# Generated by Django 5.0.6 on 2024-07-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_edit_publication', 'Can_edit_publication'), ('can_edit_dicription', 'Can_edit_dicription'), ('can_edit_category', 'Can_edit_category')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
